{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "60700159",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2025-09-20T18:07:32.484149Z",
     "iopub.status.busy": "2025-09-20T18:07:32.483803Z",
     "iopub.status.idle": "2025-09-20T18:07:38.383820Z",
     "shell.execute_reply": "2025-09-20T18:07:38.382387Z"
    },
    "papermill": {
     "duration": 5.906595,
     "end_time": "2025-09-20T18:07:38.385888",
     "exception": false,
     "start_time": "2025-09-20T18:07:32.479293",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.3)\r\n",
      "Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (1.26.4)\r\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)\r\n",
      "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)\r\n",
      "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)\r\n",
      "Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.2->pandas) (1.3.8)\r\n",
      "Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.2->pandas) (1.2.4)\r\n",
      "Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.2->pandas) (0.1.1)\r\n",
      "Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.2->pandas) (2025.2.0)\r\n",
      "Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.2->pandas) (2022.2.0)\r\n",
      "Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.2->pandas) (2.4.1)\r\n",
      "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\r\n",
      "Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.23.2->pandas) (2024.2.0)\r\n",
      "Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.23.2->pandas) (2022.2.0)\r\n",
      "Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy>=1.23.2->pandas) (1.4.0)\r\n",
      "Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy>=1.23.2->pandas) (2024.2.0)\r\n",
      "Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy>=1.23.2->pandas) (2024.2.0)\r\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install pandas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "175fe6a3",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2025-09-20T18:07:38.393270Z",
     "iopub.status.busy": "2025-09-20T18:07:38.392925Z",
     "iopub.status.idle": "2025-09-20T18:07:45.692919Z",
     "shell.execute_reply": "2025-09-20T18:07:45.691269Z"
    },
    "papermill": {
     "duration": 7.305961,
     "end_time": "2025-09-20T18:07:45.695044",
     "exception": false,
     "start_time": "2025-09-20T18:07:38.389083",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting googlemaps\r\n",
      "  Downloading googlemaps-4.10.0.tar.gz (33 kB)\r\n",
      "  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\r\n",
      "Requirement already satisfied: requests<3.0,>=2.20.0 in /usr/local/lib/python3.11/dist-packages (from googlemaps) (2.32.4)\r\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (3.4.2)\r\n",
      "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (3.10)\r\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (2.5.0)\r\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (2025.6.15)\r\n",
      "Building wheels for collected packages: googlemaps\r\n",
      "  Building wheel for googlemaps (setup.py) ... \u001b[?25l\u001b[?25hdone\r\n",
      "  Created wheel for googlemaps: filename=googlemaps-4.10.0-py3-none-any.whl size=40714 sha256=177b1f198408fb71fbe9fca919b21fc89574d1739802b5dfc35470ec42d3f5f2\r\n",
      "  Stored in directory: /root/.cache/pip/wheels/f1/09/77/3cc2f5659cbc62341b30f806aca2b25e6a26c351daa5b1f49a\r\n",
      "Successfully built googlemaps\r\n",
      "Installing collected packages: googlemaps\r\n",
      "Successfully installed googlemaps-4.10.0\r\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install googlemaps"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "93cb88cd",
   "metadata": {
    "_cell_guid": "b1076dfc-b9ad-4769-8c92-a6c4dae69d19",
    "_uuid": "8f2839f25d086af736a60e9eeb907d3b93b6e0e5",
    "execution": {
     "iopub.execute_input": "2025-09-20T18:07:45.703087Z",
     "iopub.status.busy": "2025-09-20T18:07:45.702730Z",
     "iopub.status.idle": "2025-09-20T18:07:59.798557Z",
     "shell.execute_reply": "2025-09-20T18:07:59.797323Z"
    },
    "papermill": {
     "duration": 14.102456,
     "end_time": "2025-09-20T18:07:59.800370",
     "exception": false,
     "start_time": "2025-09-20T18:07:45.697914",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Begin finding shortest route\n",
      "Waypoints file found. Loading data.\n",
      "Searching for optimal route.\n",
      "Generation 0 best: 89620752 | Unique genomes: 100\n",
      "('Graceland, Elvis Presley Boulevard, Memphis, TN', 'New Castle Historic District, Delaware', 'Spring Grove Cemetery, Spring Grove Avenue, Cincinnati, OH', 'Okefenokee Swamp Park, Okefenokee Swamp Park Road, Waycross, GA', 'Lost World Caverns, Lewisburg, WV', 'Maryland State House, 100 State Cir, Annapolis, MD 21401', 'Terrace Hill, Grand Avenue, Des Moines, IA', 'Fort Snelling, Tower Avenue, Saint Paul, MN', \"Fort Sumter National Monument, Sullivan's Island, SC\", 'French Quarter, New Orleans, LA', 'San Andreas Fault, San Benito County, CA', 'Mount Vernon, Fairfax County, Virginia', 'USS Constitution, Boston, MA', 'C. W. Parker Carousel Museum, South Esplanade Street, Leavenworth, KS', 'Cape Canaveral, FL', 'Congress Hall, Congress Place, Cape May, NJ 08204', 'Toltec Mounds, Scott, AR', 'USS Alabama, Battleship Parkway, Mobile, AL', 'Yellowstone National Park, WY 82190', 'Liberty Bell, 6th Street, Philadelphia, PA', 'Hanford Site, Benton County, WA', 'Columbia River Gorge National Scenic Area, Oregon', 'Wright Brothers National Memorial Visitor Center, Manteo, NC', 'The Mark Twain House & Museum, Farmington Avenue, Hartford, CT', 'Omni Mount Washington Resort, Mount Washington Hotel Road, Bretton Woods, NH', 'Shelburne Farms, Harbor Road, Shelburne, VT', 'Chickasaw National Recreation Area, 1008 W 2nd St, Sulphur, OK 73086', 'Lincoln Home National Historic Site Visitor Center, 426 South 7th Street, Springfield, IL', 'Mount Rushmore National Memorial, South Dakota 244, Keystone, SD', 'Cable Car Museum, 94108, 1201 Mason St, San Francisco, CA 94108', 'Bryce Canyon National Park, Hwy 63, Bryce, UT', 'Pikes Peak, Colorado', 'Ashfall Fossil Bed, Royal, NE', 'Olympia Entertainment, Woodward Avenue, Detroit, MI', 'Hoover Dam, NV', 'Fort Union Trading Post National Historic Site, Williston, North Dakota 1804, ND', 'Vicksburg National Military Park, Clay Street, Vicksburg, MS', 'Grand Canyon National Park, Arizona', 'Glacier National Park, West Glacier, MT', 'The Alamo, Alamo Plaza, San Antonio, TX', 'Carlsbad Caverns National Park, Carlsbad, NM', 'The Breakers, Ochre Point Avenue, Newport, RI', 'Statue of Liberty, Liberty Island, NYC, NY', 'Gateway Arch, Washington Avenue, St Louis, MO', 'Taliesin, County Road C, Spring Green, Wisconsin', 'Craters of the Moon National Monument & Preserve, Arco, ID', 'Mammoth Cave National Park, Mammoth Cave Pkwy, Mammoth Cave, KY', 'White House, Pennsylvania Avenue Northwest, Washington, DC', 'Acadia National Park, Maine', 'West Baden Springs Hotel, West Baden Avenue, West Baden Springs, IN')\n",
      "\n",
      "Generation 500 best: 24650188 | Unique genomes: 94\n",
      "('Grand Canyon National Park, Arizona', 'Bryce Canyon National Park, Hwy 63, Bryce, UT', 'Fort Union Trading Post National Historic Site, Williston, North Dakota 1804, ND', 'Mount Rushmore National Memorial, South Dakota 244, Keystone, SD', 'Ashfall Fossil Bed, Royal, NE', 'Fort Snelling, Tower Avenue, Saint Paul, MN', 'Taliesin, County Road C, Spring Green, Wisconsin', 'Terrace Hill, Grand Avenue, Des Moines, IA', 'C. W. Parker Carousel Museum, South Esplanade Street, Leavenworth, KS', 'Graceland, Elvis Presley Boulevard, Memphis, TN', 'Vicksburg National Military Park, Clay Street, Vicksburg, MS', 'Toltec Mounds, Scott, AR', 'Gateway Arch, Washington Avenue, St Louis, MO', 'Lincoln Home National Historic Site Visitor Center, 426 South 7th Street, Springfield, IL', 'Olympia Entertainment, Woodward Avenue, Detroit, MI', 'Spring Grove Cemetery, Spring Grove Avenue, Cincinnati, OH', 'West Baden Springs Hotel, West Baden Avenue, West Baden Springs, IN', 'Mammoth Cave National Park, Mammoth Cave Pkwy, Mammoth Cave, KY', 'Lost World Caverns, Lewisburg, WV', 'Mount Vernon, Fairfax County, Virginia', 'White House, Pennsylvania Avenue Northwest, Washington, DC', 'Maryland State House, 100 State Cir, Annapolis, MD 21401', 'Congress Hall, Congress Place, Cape May, NJ 08204', 'Liberty Bell, 6th Street, Philadelphia, PA', 'Statue of Liberty, Liberty Island, NYC, NY', 'The Mark Twain House & Museum, Farmington Avenue, Hartford, CT', 'The Breakers, Ochre Point Avenue, Newport, RI', 'USS Constitution, Boston, MA', 'Acadia National Park, Maine', 'Omni Mount Washington Resort, Mount Washington Hotel Road, Bretton Woods, NH', 'Shelburne Farms, Harbor Road, Shelburne, VT', 'New Castle Historic District, Delaware', 'Wright Brothers National Memorial Visitor Center, Manteo, NC', \"Fort Sumter National Monument, Sullivan's Island, SC\", 'Cape Canaveral, FL', 'Okefenokee Swamp Park, Okefenokee Swamp Park Road, Waycross, GA', 'USS Alabama, Battleship Parkway, Mobile, AL', 'French Quarter, New Orleans, LA', 'The Alamo, Alamo Plaza, San Antonio, TX', 'Chickasaw National Recreation Area, 1008 W 2nd St, Sulphur, OK 73086', 'Carlsbad Caverns National Park, Carlsbad, NM', 'Pikes Peak, Colorado', 'Yellowstone National Park, WY 82190', 'Craters of the Moon National Monument & Preserve, Arco, ID', 'Glacier National Park, West Glacier, MT', 'Hanford Site, Benton County, WA', 'Columbia River Gorge National Scenic Area, Oregon', 'Cable Car Museum, 94108, 1201 Mason St, San Francisco, CA 94108', 'San Andreas Fault, San Benito County, CA', 'Hoover Dam, NV')\n",
      "\n",
      "Generation 1000 best: 23110289 | Unique genomes: 96\n",
      "('Graceland, Elvis Presley Boulevard, Memphis, TN', 'Toltec Mounds, Scott, AR', 'Chickasaw National Recreation Area, 1008 W 2nd St, Sulphur, OK 73086', 'The Alamo, Alamo Plaza, San Antonio, TX', 'Carlsbad Caverns National Park, Carlsbad, NM', 'Pikes Peak, Colorado', 'Yellowstone National Park, WY 82190', 'Hanford Site, Benton County, WA', 'Columbia River Gorge National Scenic Area, Oregon', 'Cable Car Museum, 94108, 1201 Mason St, San Francisco, CA 94108', 'San Andreas Fault, San Benito County, CA', 'Hoover Dam, NV', 'Grand Canyon National Park, Arizona', 'Bryce Canyon National Park, Hwy 63, Bryce, UT', 'Craters of the Moon National Monument & Preserve, Arco, ID', 'Glacier National Park, West Glacier, MT', 'Fort Union Trading Post National Historic Site, Williston, North Dakota 1804, ND', 'Mount Rushmore National Memorial, South Dakota 244, Keystone, SD', 'Ashfall Fossil Bed, Royal, NE', 'Fort Snelling, Tower Avenue, Saint Paul, MN', 'Taliesin, County Road C, Spring Green, Wisconsin', 'Terrace Hill, Grand Avenue, Des Moines, IA', 'C. W. Parker Carousel Museum, South Esplanade Street, Leavenworth, KS', 'Gateway Arch, Washington Avenue, St Louis, MO', 'Lincoln Home National Historic Site Visitor Center, 426 South 7th Street, Springfield, IL', 'West Baden Springs Hotel, West Baden Avenue, West Baden Springs, IN', 'Mammoth Cave National Park, Mammoth Cave Pkwy, Mammoth Cave, KY', 'Spring Grove Cemetery, Spring Grove Avenue, Cincinnati, OH', 'Olympia Entertainment, Woodward Avenue, Detroit, MI', 'Lost World Caverns, Lewisburg, WV', 'Mount Vernon, Fairfax County, Virginia', 'White House, Pennsylvania Avenue Northwest, Washington, DC', 'Maryland State House, 100 State Cir, Annapolis, MD 21401', 'Liberty Bell, 6th Street, Philadelphia, PA', 'Statue of Liberty, Liberty Island, NYC, NY', 'The Mark Twain House & Museum, Farmington Avenue, Hartford, CT', 'The Breakers, Ochre Point Avenue, Newport, RI', 'USS Constitution, Boston, MA', 'Acadia National Park, Maine', 'Omni Mount Washington Resort, Mount Washington Hotel Road, Bretton Woods, NH', 'Shelburne Farms, Harbor Road, Shelburne, VT', 'Congress Hall, Congress Place, Cape May, NJ 08204', 'New Castle Historic District, Delaware', 'Wright Brothers National Memorial Visitor Center, Manteo, NC', \"Fort Sumter National Monument, Sullivan's Island, SC\", 'Okefenokee Swamp Park, Okefenokee Swamp Park Road, Waycross, GA', 'Cape Canaveral, FL', 'USS Alabama, Battleship Parkway, Mobile, AL', 'French Quarter, New Orleans, LA', 'Vicksburg National Military Park, Clay Street, Vicksburg, MS')\n",
      "\n",
      "Generation 1500 best: 23082822 | Unique genomes: 95\n",
      "('Wright Brothers National Memorial Visitor Center, Manteo, NC', \"Fort Sumter National Monument, Sullivan's Island, SC\", 'Okefenokee Swamp Park, Okefenokee Swamp Park Road, Waycross, GA', 'Cape Canaveral, FL', 'USS Alabama, Battleship Parkway, Mobile, AL', 'French Quarter, New Orleans, LA', 'Vicksburg National Military Park, Clay Street, Vicksburg, MS', 'Graceland, Elvis Presley Boulevard, Memphis, TN', 'Toltec Mounds, Scott, AR', 'Chickasaw National Recreation Area, 1008 W 2nd St, Sulphur, OK 73086', 'The Alamo, Alamo Plaza, San Antonio, TX', 'Carlsbad Caverns National Park, Carlsbad, NM', 'Pikes Peak, Colorado', 'Yellowstone National Park, WY 82190', 'Glacier National Park, West Glacier, MT', 'Hanford Site, Benton County, WA', 'Columbia River Gorge National Scenic Area, Oregon', 'Cable Car Museum, 94108, 1201 Mason St, San Francisco, CA 94108', 'San Andreas Fault, San Benito County, CA', 'Hoover Dam, NV', 'Grand Canyon National Park, Arizona', 'Bryce Canyon National Park, Hwy 63, Bryce, UT', 'Craters of the Moon National Monument & Preserve, Arco, ID', 'Fort Union Trading Post National Historic Site, Williston, North Dakota 1804, ND', 'Mount Rushmore National Memorial, South Dakota 244, Keystone, SD', 'Ashfall Fossil Bed, Royal, NE', 'Fort Snelling, Tower Avenue, Saint Paul, MN', 'Taliesin, County Road C, Spring Green, Wisconsin', 'Terrace Hill, Grand Avenue, Des Moines, IA', 'C. W. Parker Carousel Museum, South Esplanade Street, Leavenworth, KS', 'Gateway Arch, Washington Avenue, St Louis, MO', 'Lincoln Home National Historic Site Visitor Center, 426 South 7th Street, Springfield, IL', 'West Baden Springs Hotel, West Baden Avenue, West Baden Springs, IN', 'Mammoth Cave National Park, Mammoth Cave Pkwy, Mammoth Cave, KY', 'Spring Grove Cemetery, Spring Grove Avenue, Cincinnati, OH', 'Olympia Entertainment, Woodward Avenue, Detroit, MI', 'Lost World Caverns, Lewisburg, WV', 'Mount Vernon, Fairfax County, Virginia', 'White House, Pennsylvania Avenue Northwest, Washington, DC', 'Maryland State House, 100 State Cir, Annapolis, MD 21401', 'New Castle Historic District, Delaware', 'Liberty Bell, 6th Street, Philadelphia, PA', 'Statue of Liberty, Liberty Island, NYC, NY', 'The Mark Twain House & Museum, Farmington Avenue, Hartford, CT', 'The Breakers, Ochre Point Avenue, Newport, RI', 'USS Constitution, Boston, MA', 'Acadia National Park, Maine', 'Omni Mount Washington Resort, Mount Washington Hotel Road, Bretton Woods, NH', 'Shelburne Farms, Harbor Road, Shelburne, VT', 'Congress Hall, Congress Place, Cape May, NJ 08204')\n",
      "\n",
      "Generation 2000 best: 22560975 | Unique genomes: 97\n",
      "('Ashfall Fossil Bed, Royal, NE', 'Fort Snelling, Tower Avenue, Saint Paul, MN', 'Taliesin, County Road C, Spring Green, Wisconsin', 'Terrace Hill, Grand Avenue, Des Moines, IA', 'C. W. Parker Carousel Museum, South Esplanade Street, Leavenworth, KS', 'Gateway Arch, Washington Avenue, St Louis, MO', 'Lincoln Home National Historic Site Visitor Center, 426 South 7th Street, Springfield, IL', 'West Baden Springs Hotel, West Baden Avenue, West Baden Springs, IN', 'Mammoth Cave National Park, Mammoth Cave Pkwy, Mammoth Cave, KY', 'Spring Grove Cemetery, Spring Grove Avenue, Cincinnati, OH', 'Olympia Entertainment, Woodward Avenue, Detroit, MI', 'Lost World Caverns, Lewisburg, WV', 'Mount Vernon, Fairfax County, Virginia', 'White House, Pennsylvania Avenue Northwest, Washington, DC', 'Maryland State House, 100 State Cir, Annapolis, MD 21401', 'New Castle Historic District, Delaware', 'Liberty Bell, 6th Street, Philadelphia, PA', 'Statue of Liberty, Liberty Island, NYC, NY', 'The Mark Twain House & Museum, Farmington Avenue, Hartford, CT', 'The Breakers, Ochre Point Avenue, Newport, RI', 'USS Constitution, Boston, MA', 'Acadia National Park, Maine', 'Omni Mount Washington Resort, Mount Washington Hotel Road, Bretton Woods, NH', 'Shelburne Farms, Harbor Road, Shelburne, VT', 'Congress Hall, Congress Place, Cape May, NJ 08204', 'Wright Brothers National Memorial Visitor Center, Manteo, NC', \"Fort Sumter National Monument, Sullivan's Island, SC\", 'Okefenokee Swamp Park, Okefenokee Swamp Park Road, Waycross, GA', 'Cape Canaveral, FL', 'USS Alabama, Battleship Parkway, Mobile, AL', 'French Quarter, New Orleans, LA', 'Vicksburg National Military Park, Clay Street, Vicksburg, MS', 'Graceland, Elvis Presley Boulevard, Memphis, TN', 'Toltec Mounds, Scott, AR', 'Chickasaw National Recreation Area, 1008 W 2nd St, Sulphur, OK 73086', 'The Alamo, Alamo Plaza, San Antonio, TX', 'Carlsbad Caverns National Park, Carlsbad, NM', 'Pikes Peak, Colorado', 'Mount Rushmore National Memorial, South Dakota 244, Keystone, SD', 'Fort Union Trading Post National Historic Site, Williston, North Dakota 1804, ND', 'Glacier National Park, West Glacier, MT', 'Hanford Site, Benton County, WA', 'Columbia River Gorge National Scenic Area, Oregon', 'Cable Car Museum, 94108, 1201 Mason St, San Francisco, CA 94108', 'San Andreas Fault, San Benito County, CA', 'Hoover Dam, NV', 'Grand Canyon National Park, Arizona', 'Bryce Canyon National Park, Hwy 63, Bryce, UT', 'Craters of the Moon National Monument & Preserve, Arco, ID', 'Yellowstone National Park, WY 82190')\n",
      "\n",
      "Generation 2500 best: 22560975 | Unique genomes: 97\n",
      "('Ashfall Fossil Bed, Royal, NE', 'Fort Snelling, Tower Avenue, Saint Paul, MN', 'Taliesin, County Road C, Spring Green, Wisconsin', 'Terrace Hill, Grand Avenue, Des Moines, IA', 'C. W. Parker Carousel Museum, South Esplanade Street, Leavenworth, KS', 'Gateway Arch, Washington Avenue, St Louis, MO', 'Lincoln Home National Historic Site Visitor Center, 426 South 7th Street, Springfield, IL', 'West Baden Springs Hotel, West Baden Avenue, West Baden Springs, IN', 'Mammoth Cave National Park, Mammoth Cave Pkwy, Mammoth Cave, KY', 'Spring Grove Cemetery, Spring Grove Avenue, Cincinnati, OH', 'Olympia Entertainment, Woodward Avenue, Detroit, MI', 'Lost World Caverns, Lewisburg, WV', 'Mount Vernon, Fairfax County, Virginia', 'White House, Pennsylvania Avenue Northwest, Washington, DC', 'Maryland State House, 100 State Cir, Annapolis, MD 21401', 'New Castle Historic District, Delaware', 'Liberty Bell, 6th Street, Philadelphia, PA', 'Statue of Liberty, Liberty Island, NYC, NY', 'The Mark Twain House & Museum, Farmington Avenue, Hartford, CT', 'The Breakers, Ochre Point Avenue, Newport, RI', 'USS Constitution, Boston, MA', 'Acadia National Park, Maine', 'Omni Mount Washington Resort, Mount Washington Hotel Road, Bretton Woods, NH', 'Shelburne Farms, Harbor Road, Shelburne, VT', 'Congress Hall, Congress Place, Cape May, NJ 08204', 'Wright Brothers National Memorial Visitor Center, Manteo, NC', \"Fort Sumter National Monument, Sullivan's Island, SC\", 'Okefenokee Swamp Park, Okefenokee Swamp Park Road, Waycross, GA', 'Cape Canaveral, FL', 'USS Alabama, Battleship Parkway, Mobile, AL', 'French Quarter, New Orleans, LA', 'Vicksburg National Military Park, Clay Street, Vicksburg, MS', 'Graceland, Elvis Presley Boulevard, Memphis, TN', 'Toltec Mounds, Scott, AR', 'Chickasaw National Recreation Area, 1008 W 2nd St, Sulphur, OK 73086', 'The Alamo, Alamo Plaza, San Antonio, TX', 'Carlsbad Caverns National Park, Carlsbad, NM', 'Pikes Peak, Colorado', 'Mount Rushmore National Memorial, South Dakota 244, Keystone, SD', 'Fort Union Trading Post National Historic Site, Williston, North Dakota 1804, ND', 'Glacier National Park, West Glacier, MT', 'Hanford Site, Benton County, WA', 'Columbia River Gorge National Scenic Area, Oregon', 'Cable Car Museum, 94108, 1201 Mason St, San Francisco, CA 94108', 'San Andreas Fault, San Benito County, CA', 'Hoover Dam, NV', 'Grand Canyon National Park, Arizona', 'Bryce Canyon National Park, Hwy 63, Bryce, UT', 'Craters of the Moon National Monument & Preserve, Arco, ID', 'Yellowstone National Park, WY 82190')\n",
      "\n",
      "Generation 3000 best: 22560975 | Unique genomes: 97\n",
      "('Ashfall Fossil Bed, Royal, NE', 'Fort Snelling, Tower Avenue, Saint Paul, MN', 'Taliesin, County Road C, Spring Green, Wisconsin', 'Terrace Hill, Grand Avenue, Des Moines, IA', 'C. W. Parker Carousel Museum, South Esplanade Street, Leavenworth, KS', 'Gateway Arch, Washington Avenue, St Louis, MO', 'Lincoln Home National Historic Site Visitor Center, 426 South 7th Street, Springfield, IL', 'West Baden Springs Hotel, West Baden Avenue, West Baden Springs, IN', 'Mammoth Cave National Park, Mammoth Cave Pkwy, Mammoth Cave, KY', 'Spring Grove Cemetery, Spring Grove Avenue, Cincinnati, OH', 'Olympia Entertainment, Woodward Avenue, Detroit, MI', 'Lost World Caverns, Lewisburg, WV', 'Mount Vernon, Fairfax County, Virginia', 'White House, Pennsylvania Avenue Northwest, Washington, DC', 'Maryland State House, 100 State Cir, Annapolis, MD 21401', 'New Castle Historic District, Delaware', 'Liberty Bell, 6th Street, Philadelphia, PA', 'Statue of Liberty, Liberty Island, NYC, NY', 'The Mark Twain House & Museum, Farmington Avenue, Hartford, CT', 'The Breakers, Ochre Point Avenue, Newport, RI', 'USS Constitution, Boston, MA', 'Acadia National Park, Maine', 'Omni Mount Washington Resort, Mount Washington Hotel Road, Bretton Woods, NH', 'Shelburne Farms, Harbor Road, Shelburne, VT', 'Congress Hall, Congress Place, Cape May, NJ 08204', 'Wright Brothers National Memorial Visitor Center, Manteo, NC', \"Fort Sumter National Monument, Sullivan's Island, SC\", 'Okefenokee Swamp Park, Okefenokee Swamp Park Road, Waycross, GA', 'Cape Canaveral, FL', 'USS Alabama, Battleship Parkway, Mobile, AL', 'French Quarter, New Orleans, LA', 'Vicksburg National Military Park, Clay Street, Vicksburg, MS', 'Graceland, Elvis Presley Boulevard, Memphis, TN', 'Toltec Mounds, Scott, AR', 'Chickasaw National Recreation Area, 1008 W 2nd St, Sulphur, OK 73086', 'The Alamo, Alamo Plaza, San Antonio, TX', 'Carlsbad Caverns National Park, Carlsbad, NM', 'Pikes Peak, Colorado', 'Mount Rushmore National Memorial, South Dakota 244, Keystone, SD', 'Fort Union Trading Post National Historic Site, Williston, North Dakota 1804, ND', 'Glacier National Park, West Glacier, MT', 'Hanford Site, Benton County, WA', 'Columbia River Gorge National Scenic Area, Oregon', 'Cable Car Museum, 94108, 1201 Mason St, San Francisco, CA 94108', 'San Andreas Fault, San Benito County, CA', 'Hoover Dam, NV', 'Grand Canyon National Park, Arizona', 'Bryce Canyon National Park, Hwy 63, Bryce, UT', 'Craters of the Moon National Monument & Preserve, Arco, ID', 'Yellowstone National Park, WY 82190')\n",
      "\n",
      "Generation 3500 best: 22560975 | Unique genomes: 99\n",
      "('Ashfall Fossil Bed, Royal, NE', 'Fort Snelling, Tower Avenue, Saint Paul, MN', 'Taliesin, County Road C, Spring Green, Wisconsin', 'Terrace Hill, Grand Avenue, Des Moines, IA', 'C. W. Parker Carousel Museum, South Esplanade Street, Leavenworth, KS', 'Gateway Arch, Washington Avenue, St Louis, MO', 'Lincoln Home National Historic Site Visitor Center, 426 South 7th Street, Springfield, IL', 'West Baden Springs Hotel, West Baden Avenue, West Baden Springs, IN', 'Mammoth Cave National Park, Mammoth Cave Pkwy, Mammoth Cave, KY', 'Spring Grove Cemetery, Spring Grove Avenue, Cincinnati, OH', 'Olympia Entertainment, Woodward Avenue, Detroit, MI', 'Lost World Caverns, Lewisburg, WV', 'Mount Vernon, Fairfax County, Virginia', 'White House, Pennsylvania Avenue Northwest, Washington, DC', 'Maryland State House, 100 State Cir, Annapolis, MD 21401', 'New Castle Historic District, Delaware', 'Liberty Bell, 6th Street, Philadelphia, PA', 'Statue of Liberty, Liberty Island, NYC, NY', 'The Mark Twain House & Museum, Farmington Avenue, Hartford, CT', 'The Breakers, Ochre Point Avenue, Newport, RI', 'USS Constitution, Boston, MA', 'Acadia National Park, Maine', 'Omni Mount Washington Resort, Mount Washington Hotel Road, Bretton Woods, NH', 'Shelburne Farms, Harbor Road, Shelburne, VT', 'Congress Hall, Congress Place, Cape May, NJ 08204', 'Wright Brothers National Memorial Visitor Center, Manteo, NC', \"Fort Sumter National Monument, Sullivan's Island, SC\", 'Okefenokee Swamp Park, Okefenokee Swamp Park Road, Waycross, GA', 'Cape Canaveral, FL', 'USS Alabama, Battleship Parkway, Mobile, AL', 'French Quarter, New Orleans, LA', 'Vicksburg National Military Park, Clay Street, Vicksburg, MS', 'Graceland, Elvis Presley Boulevard, Memphis, TN', 'Toltec Mounds, Scott, AR', 'Chickasaw National Recreation Area, 1008 W 2nd St, Sulphur, OK 73086', 'The Alamo, Alamo Plaza, San Antonio, TX', 'Carlsbad Caverns National Park, Carlsbad, NM', 'Pikes Peak, Colorado', 'Mount Rushmore National Memorial, South Dakota 244, Keystone, SD', 'Fort Union Trading Post National Historic Site, Williston, North Dakota 1804, ND', 'Glacier National Park, West Glacier, MT', 'Hanford Site, Benton County, WA', 'Columbia River Gorge National Scenic Area, Oregon', 'Cable Car Museum, 94108, 1201 Mason St, San Francisco, CA 94108', 'San Andreas Fault, San Benito County, CA', 'Hoover Dam, NV', 'Grand Canyon National Park, Arizona', 'Bryce Canyon National Park, Hwy 63, Bryce, UT', 'Craters of the Moon National Monument & Preserve, Arco, ID', 'Yellowstone National Park, WY 82190')\n",
      "\n",
      "Generation 4000 best: 22560975 | Unique genomes: 93\n",
      "('Ashfall Fossil Bed, Royal, NE', 'Fort Snelling, Tower Avenue, Saint Paul, MN', 'Taliesin, County Road C, Spring Green, Wisconsin', 'Terrace Hill, Grand Avenue, Des Moines, IA', 'C. W. Parker Carousel Museum, South Esplanade Street, Leavenworth, KS', 'Gateway Arch, Washington Avenue, St Louis, MO', 'Lincoln Home National Historic Site Visitor Center, 426 South 7th Street, Springfield, IL', 'West Baden Springs Hotel, West Baden Avenue, West Baden Springs, IN', 'Mammoth Cave National Park, Mammoth Cave Pkwy, Mammoth Cave, KY', 'Spring Grove Cemetery, Spring Grove Avenue, Cincinnati, OH', 'Olympia Entertainment, Woodward Avenue, Detroit, MI', 'Lost World Caverns, Lewisburg, WV', 'Mount Vernon, Fairfax County, Virginia', 'White House, Pennsylvania Avenue Northwest, Washington, DC', 'Maryland State House, 100 State Cir, Annapolis, MD 21401', 'New Castle Historic District, Delaware', 'Liberty Bell, 6th Street, Philadelphia, PA', 'Statue of Liberty, Liberty Island, NYC, NY', 'The Mark Twain House & Museum, Farmington Avenue, Hartford, CT', 'The Breakers, Ochre Point Avenue, Newport, RI', 'USS Constitution, Boston, MA', 'Acadia National Park, Maine', 'Omni Mount Washington Resort, Mount Washington Hotel Road, Bretton Woods, NH', 'Shelburne Farms, Harbor Road, Shelburne, VT', 'Congress Hall, Congress Place, Cape May, NJ 08204', 'Wright Brothers National Memorial Visitor Center, Manteo, NC', \"Fort Sumter National Monument, Sullivan's Island, SC\", 'Okefenokee Swamp Park, Okefenokee Swamp Park Road, Waycross, GA', 'Cape Canaveral, FL', 'USS Alabama, Battleship Parkway, Mobile, AL', 'French Quarter, New Orleans, LA', 'Vicksburg National Military Park, Clay Street, Vicksburg, MS', 'Graceland, Elvis Presley Boulevard, Memphis, TN', 'Toltec Mounds, Scott, AR', 'Chickasaw National Recreation Area, 1008 W 2nd St, Sulphur, OK 73086', 'The Alamo, Alamo Plaza, San Antonio, TX', 'Carlsbad Caverns National Park, Carlsbad, NM', 'Pikes Peak, Colorado', 'Mount Rushmore National Memorial, South Dakota 244, Keystone, SD', 'Fort Union Trading Post National Historic Site, Williston, North Dakota 1804, ND', 'Glacier National Park, West Glacier, MT', 'Hanford Site, Benton County, WA', 'Columbia River Gorge National Scenic Area, Oregon', 'Cable Car Museum, 94108, 1201 Mason St, San Francisco, CA 94108', 'San Andreas Fault, San Benito County, CA', 'Hoover Dam, NV', 'Grand Canyon National Park, Arizona', 'Bryce Canyon National Park, Hwy 63, Bryce, UT', 'Craters of the Moon National Monument & Preserve, Arco, ID', 'Yellowstone National Park, WY 82190')\n",
      "\n",
      "Generation 4500 best: 22560975 | Unique genomes: 99\n",
      "('Ashfall Fossil Bed, Royal, NE', 'Fort Snelling, Tower Avenue, Saint Paul, MN', 'Taliesin, County Road C, Spring Green, Wisconsin', 'Terrace Hill, Grand Avenue, Des Moines, IA', 'C. W. Parker Carousel Museum, South Esplanade Street, Leavenworth, KS', 'Gateway Arch, Washington Avenue, St Louis, MO', 'Lincoln Home National Historic Site Visitor Center, 426 South 7th Street, Springfield, IL', 'West Baden Springs Hotel, West Baden Avenue, West Baden Springs, IN', 'Mammoth Cave National Park, Mammoth Cave Pkwy, Mammoth Cave, KY', 'Spring Grove Cemetery, Spring Grove Avenue, Cincinnati, OH', 'Olympia Entertainment, Woodward Avenue, Detroit, MI', 'Lost World Caverns, Lewisburg, WV', 'Mount Vernon, Fairfax County, Virginia', 'White House, Pennsylvania Avenue Northwest, Washington, DC', 'Maryland State House, 100 State Cir, Annapolis, MD 21401', 'New Castle Historic District, Delaware', 'Liberty Bell, 6th Street, Philadelphia, PA', 'Statue of Liberty, Liberty Island, NYC, NY', 'The Mark Twain House & Museum, Farmington Avenue, Hartford, CT', 'The Breakers, Ochre Point Avenue, Newport, RI', 'USS Constitution, Boston, MA', 'Acadia National Park, Maine', 'Omni Mount Washington Resort, Mount Washington Hotel Road, Bretton Woods, NH', 'Shelburne Farms, Harbor Road, Shelburne, VT', 'Congress Hall, Congress Place, Cape May, NJ 08204', 'Wright Brothers National Memorial Visitor Center, Manteo, NC', \"Fort Sumter National Monument, Sullivan's Island, SC\", 'Okefenokee Swamp Park, Okefenokee Swamp Park Road, Waycross, GA', 'Cape Canaveral, FL', 'USS Alabama, Battleship Parkway, Mobile, AL', 'French Quarter, New Orleans, LA', 'Vicksburg National Military Park, Clay Street, Vicksburg, MS', 'Graceland, Elvis Presley Boulevard, Memphis, TN', 'Toltec Mounds, Scott, AR', 'Chickasaw National Recreation Area, 1008 W 2nd St, Sulphur, OK 73086', 'The Alamo, Alamo Plaza, San Antonio, TX', 'Carlsbad Caverns National Park, Carlsbad, NM', 'Pikes Peak, Colorado', 'Mount Rushmore National Memorial, South Dakota 244, Keystone, SD', 'Fort Union Trading Post National Historic Site, Williston, North Dakota 1804, ND', 'Glacier National Park, West Glacier, MT', 'Hanford Site, Benton County, WA', 'Columbia River Gorge National Scenic Area, Oregon', 'Cable Car Museum, 94108, 1201 Mason St, San Francisco, CA 94108', 'San Andreas Fault, San Benito County, CA', 'Hoover Dam, NV', 'Grand Canyon National Park, Arizona', 'Bryce Canyon National Park, Hwy 63, Bryce, UT', 'Craters of the Moon National Monument & Preserve, Arco, ID', 'Yellowstone National Park, WY 82190')\n",
      "\n",
      "Generation 4999 best: 22560975 | Unique genomes: 98\n",
      "('Ashfall Fossil Bed, Royal, NE', 'Fort Snelling, Tower Avenue, Saint Paul, MN', 'Taliesin, County Road C, Spring Green, Wisconsin', 'Terrace Hill, Grand Avenue, Des Moines, IA', 'C. W. Parker Carousel Museum, South Esplanade Street, Leavenworth, KS', 'Gateway Arch, Washington Avenue, St Louis, MO', 'Lincoln Home National Historic Site Visitor Center, 426 South 7th Street, Springfield, IL', 'West Baden Springs Hotel, West Baden Avenue, West Baden Springs, IN', 'Mammoth Cave National Park, Mammoth Cave Pkwy, Mammoth Cave, KY', 'Spring Grove Cemetery, Spring Grove Avenue, Cincinnati, OH', 'Olympia Entertainment, Woodward Avenue, Detroit, MI', 'Lost World Caverns, Lewisburg, WV', 'Mount Vernon, Fairfax County, Virginia', 'White House, Pennsylvania Avenue Northwest, Washington, DC', 'Maryland State House, 100 State Cir, Annapolis, MD 21401', 'New Castle Historic District, Delaware', 'Liberty Bell, 6th Street, Philadelphia, PA', 'Statue of Liberty, Liberty Island, NYC, NY', 'The Mark Twain House & Museum, Farmington Avenue, Hartford, CT', 'The Breakers, Ochre Point Avenue, Newport, RI', 'USS Constitution, Boston, MA', 'Acadia National Park, Maine', 'Omni Mount Washington Resort, Mount Washington Hotel Road, Bretton Woods, NH', 'Shelburne Farms, Harbor Road, Shelburne, VT', 'Congress Hall, Congress Place, Cape May, NJ 08204', 'Wright Brothers National Memorial Visitor Center, Manteo, NC', \"Fort Sumter National Monument, Sullivan's Island, SC\", 'Okefenokee Swamp Park, Okefenokee Swamp Park Road, Waycross, GA', 'Cape Canaveral, FL', 'USS Alabama, Battleship Parkway, Mobile, AL', 'French Quarter, New Orleans, LA', 'Vicksburg National Military Park, Clay Street, Vicksburg, MS', 'Graceland, Elvis Presley Boulevard, Memphis, TN', 'Toltec Mounds, Scott, AR', 'Chickasaw National Recreation Area, 1008 W 2nd St, Sulphur, OK 73086', 'The Alamo, Alamo Plaza, San Antonio, TX', 'Carlsbad Caverns National Park, Carlsbad, NM', 'Pikes Peak, Colorado', 'Mount Rushmore National Memorial, South Dakota 244, Keystone, SD', 'Fort Union Trading Post National Historic Site, Williston, North Dakota 1804, ND', 'Glacier National Park, West Glacier, MT', 'Hanford Site, Benton County, WA', 'Columbia River Gorge National Scenic Area, Oregon', 'Cable Car Museum, 94108, 1201 Mason St, San Francisco, CA 94108', 'San Andreas Fault, San Benito County, CA', 'Hoover Dam, NV', 'Grand Canyon National Park, Arizona', 'Bryce Canyon National Park, Hwy 63, Bryce, UT', 'Craters of the Moon National Monument & Preserve, Arco, ID', 'Yellowstone National Park, WY 82190')\n",
      "\n"
     ]
    }
   ],
   "source": [
    "from __future__ import print_function\n",
    "from itertools import combinations\n",
    "import googlemaps\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import os.path\n",
    "import random\n",
    "import webbrowser\n",
    "\n",
    "# Google Maps API key needs to be added here.\n",
    "GOOGLE_MAPS_API_KEY = \"Add you own API\"\n",
    "\n",
    "# Path to the waypoints file.\n",
    "waypoints_file = \"/kaggle/input/my-waypoints-dist-dur/my-waypoints-dist-dur.tsv\"\n",
    "\n",
    "# Base filename for the HTML output. A shorter route's fitness score will be appended.\n",
    "output_file = 'Output.html'\n",
    "\n",
    "# Parameters for the genetic algorithm.\n",
    "thisRunGenerations = 5000\n",
    "thisRunPopulation_size = 100\n",
    "\n",
    "# List of all waypoints (50 states + D.C.).\n",
    "all_waypoints = [\"USS Alabama, Battleship Parkway, Mobile, AL\",\n",
    "                 \"Grand Canyon National Park, Arizona\",\n",
    "                 \"Toltec Mounds, Scott, AR\",\n",
    "                 \"San Andreas Fault, San Benito County, CA\",\n",
    "                 \"Cable Car Museum, 94108, 1201 Mason St, San Francisco, CA 94108\",\n",
    "                 \"Pikes Peak, Colorado\",\n",
    "                 \"The Mark Twain House & Museum, Farmington Avenue, Hartford, CT\",\n",
    "                 \"New Castle Historic District, Delaware\",\n",
    "                 \"White House, Pennsylvania Avenue Northwest, Washington, DC\",\n",
    "                 \"Cape Canaveral, FL\",\n",
    "                 \"Okefenokee Swamp Park, Okefenokee Swamp Park Road, Waycross, GA\",\n",
    "                 \"Craters of the Moon National Monument & Preserve, Arco, ID\",\n",
    "                 \"Lincoln Home National Historic Site Visitor Center, 426 South 7th Street, Springfield, IL\",\n",
    "                 \"West Baden Springs Hotel, West Baden Avenue, West Baden Springs, IN\",\n",
    "                 \"Terrace Hill, Grand Avenue, Des Moines, IA\",\n",
    "                 \"C. W. Parker Carousel Museum, South Esplanade Street, Leavenworth, KS\",\n",
    "                 \"Mammoth Cave National Park, Mammoth Cave Pkwy, Mammoth Cave, KY\",\n",
    "                 \"French Quarter, New Orleans, LA\",\n",
    "                 \"Acadia National Park, Maine\",\n",
    "                 \"Maryland State House, 100 State Cir, Annapolis, MD 21401\",\n",
    "                 \"USS Constitution, Boston, MA\",\n",
    "                 \"Olympia Entertainment, Woodward Avenue, Detroit, MI\",\n",
    "                 \"Fort Snelling, Tower Avenue, Saint Paul, MN\",\n",
    "                 \"Vicksburg National Military Park, Clay Street, Vicksburg, MS\",\n",
    "                 \"Gateway Arch, Washington Avenue, St Louis, MO\",\n",
    "                 \"Glacier National Park, West Glacier, MT\",\n",
    "                 \"Ashfall Fossil Bed, Royal, NE\",\n",
    "                 \"Hoover Dam, NV\",\n",
    "                 \"Omni Mount Washington Resort, Mount Washington Hotel Road, Bretton Woods, NH\",\n",
    "                 \"Congress Hall, Congress Place, Cape May, NJ 08204\",\n",
    "                 \"Carlsbad Caverns National Park, Carlsbad, NM\",\n",
    "                 \"Statue of Liberty, Liberty Island, NYC, NY\",\n",
    "                 \"Wright Brothers National Memorial Visitor Center, Manteo, NC\",\n",
    "                 \"Fort Union Trading Post National Historic Site, Williston, North Dakota 1804, ND\",\n",
    "                 \"Spring Grove Cemetery, Spring Grove Avenue, Cincinnati, OH\",\n",
    "                 \"Chickasaw National Recreation Area, 1008 W 2nd St, Sulphur, OK 73086\",\n",
    "                 \"Columbia River Gorge National Scenic Area, Oregon\",\n",
    "                 \"Liberty Bell, 6th Street, Philadelphia, PA\",\n",
    "                 \"The Breakers, Ochre Point Avenue, Newport, RI\",\n",
    "                 \"Fort Sumter National Monument, Sullivan's Island, SC\",\n",
    "                 \"Mount Rushmore National Memorial, South Dakota 244, Keystone, SD\",\n",
    "                 \"Graceland, Elvis Presley Boulevard, Memphis, TN\",\n",
    "                 \"The Alamo, Alamo Plaza, San Antonio, TX\",\n",
    "                 \"Bryce Canyon National Park, Hwy 63, Bryce, UT\",\n",
    "                 \"Shelburne Farms, Harbor Road, Shelburne, VT\",\n",
    "                 \"Mount Vernon, Fairfax County, Virginia\",\n",
    "                 \"Hanford Site, Benton County, WA\",\n",
    "                 \"Lost World Caverns, Lewisburg, WV\",\n",
    "                 \"Taliesin, County Road C, Spring Green, Wisconsin\",\n",
    "                 \"Yellowstone National Park, WY 82190\"]\n",
    "\n",
    "def CreateOptimalRouteHtmlFile(optimal_route, distance, display=True):\n",
    "    \"\"\"\n",
    "    Dynamically creates and opens an HTML file displaying the route using Google Maps.\n",
    "    \n",
    "    Args:\n",
    "        optimal_route (tuple): The sequence of waypoints for the route.\n",
    "        distance (float): The total distance of the route.\n",
    "        display (bool): If True, opens the HTML file in a web browser.\n",
    "    \"\"\"\n",
    "    optimal_route = list(optimal_route)\n",
    "    optimal_route += [optimal_route[0]]\n",
    "\n",
    "    # HTML content for the Google Maps display.\n",
    "    Page_1 = \"\"\"\n",
    "    <!DOCTYPE html>\n",
    "    <html lang=\"en\">\n",
    "      <head>\n",
    "        <meta charset=\"utf-8\">\n",
    "        <meta name=\"viewport\" content=\"initial-scale=1.0, user-scalable=no\">\n",
    "        <meta name=\"description\" content=\"Optimal road trip across the U.S. using a genetic algorithm.\">\n",
    "        <meta name=\"author\" content=\"Program\">\n",
    "        \n",
    "        <title>The optimal road trip across the U.S. according to a genetic algorithm</title>\n",
    "        <style>\n",
    "          html, body, #map-canvas {\n",
    "            height: 100%;\n",
    "            margin: 0px;\n",
    "            padding: 0px\n",
    "          }\n",
    "          #panel {\n",
    "            position: absolute;\n",
    "            top: 5px;\n",
    "            left: 50%;\n",
    "            margin-left: -180px;\n",
    "            z-index: 5;\n",
    "            background-color: #fff;\n",
    "            padding: 10px;\n",
    "            border: 1px solid #999;\n",
    "          }\n",
    "        </style>\n",
    "        <script src=\"https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true\"></script>\n",
    "        <script>\n",
    "            var routes_list = []\n",
    "            var markerOptions = {icon: \"http://maps.gstatic.com/mapfiles/markers2/marker.png\"};\n",
    "            var directionsDisplayOptions = {preserveViewport: true,\n",
    "                                            markerOptions: markerOptions};\n",
    "            var directionsService = new google.maps.DirectionsService();\n",
    "            var map;\n",
    "\n",
    "            function initialize() {\n",
    "              var center = new google.maps.LatLng(39, -96);\n",
    "              var mapOptions = {\n",
    "                zoom: 5,\n",
    "                center: center\n",
    "              };\n",
    "              map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);\n",
    "              for (i=0; i<routes_list.length; i++) {\n",
    "                routes_list[i].setMap(map); \n",
    "              }\n",
    "            }\n",
    "\n",
    "            function calcRoute(start, end, routes) {\n",
    "              \n",
    "              var directionsDisplay = new google.maps.DirectionsRenderer(directionsDisplayOptions);\n",
    "\n",
    "              var waypts = [];\n",
    "              for (var i = 0; i < routes.length; i++) {\n",
    "                waypts.push({\n",
    "                  location:routes[i],\n",
    "                  stopover:true});\n",
    "                }\n",
    "              \n",
    "              var request = {\n",
    "                  origin: start,\n",
    "                  destination: end,\n",
    "                  waypoints: waypts,\n",
    "                  optimizeWaypoints: false,\n",
    "                  travelMode: google.maps.TravelMode.DRIVING\n",
    "              };\n",
    "\n",
    "              directionsService.route(request, function(response, status) {\n",
    "                if (status == google.maps.DirectionsStatus.OK) {\n",
    "                    directionsDisplay.setDirections(response);      \n",
    "                }\n",
    "              });\n",
    "\n",
    "              routes_list.push(directionsDisplay);\n",
    "            }\n",
    "\n",
    "            function createRoutes(route) {\n",
    "                // Google's free map API is limited to 10 waypoints, so need to break into batches.\n",
    "                route.push(route[0]);\n",
    "                var subset = 0;\n",
    "                while (subset < route.length) {\n",
    "                    var waypointSubset = route.slice(subset, subset + 10);\n",
    "\n",
    "                    var startPoint = waypointSubset[0];\n",
    "                    var midPoints = waypointSubset.slice(1, waypointSubset.length - 1);\n",
    "                    var endPoint = waypointSubset[waypointSubset.length - 1];\n",
    "\n",
    "                    calcRoute(startPoint, endPoint, midPoints);\n",
    "\n",
    "                    subset += 9;\n",
    "                }\n",
    "            }\n",
    "    \"\"\"\n",
    "    Page_2 = \"\"\"\n",
    "            \n",
    "            createRoutes(optimal_route);\n",
    "\n",
    "            google.maps.event.addDomListener(window, 'load', initialize);\n",
    "\n",
    "        </script>\n",
    "      </head>\n",
    "      <body>\n",
    "        <div id=\"map-canvas\"></div>\n",
    "      </body>\n",
    "    </html>\n",
    "    \"\"\"\n",
    "\n",
    "    localoutput_file = output_file.replace('.html', '_' + str(distance) + '.html')\n",
    "    with open(localoutput_file, 'w') as fs:\n",
    "        fs.write(Page_1)\n",
    "        fs.write(\"\\t\\t\\toptimal_route = {0}\".format(str(optimal_route)))\n",
    "        fs.write(Page_2)\n",
    "\n",
    "    if display:\n",
    "        webbrowser.open_new_tab(localoutput_file)\n",
    "\n",
    "def compute_fitness(solution):\n",
    "    \"\"\"\n",
    "    Calculates the total distance of a given road trip (solution).\n",
    "    The genetic algorithm aims to minimize this value.\n",
    "    \n",
    "    Args:\n",
    "        solution (tuple): A sequence of waypoints.\n",
    "    \n",
    "    Returns:\n",
    "        float: The total distance of the route in meters.\n",
    "    \"\"\"\n",
    "    \n",
    "    solution_fitness = 0.0\n",
    "    \n",
    "    for index in range(len(solution)):\n",
    "        waypoint1 = solution[index - 1]\n",
    "        waypoint2 = solution[index]\n",
    "        solution_fitness += waypoint_distances[frozenset([waypoint1, waypoint2])]\n",
    "        \n",
    "    return solution_fitness\n",
    "\n",
    "def generate_random_agent():\n",
    "    \"\"\"\n",
    "    Creates a random permutation of waypoints.\n",
    "    \n",
    "    Returns:\n",
    "        tuple: A randomly ordered sequence of all waypoints.\n",
    "    \"\"\"\n",
    "    \n",
    "    new_random_agent = list(all_waypoints)\n",
    "    random.shuffle(new_random_agent)\n",
    "    return tuple(new_random_agent)\n",
    "\n",
    "def mutate_agent(agent_genome, max_mutations=3):\n",
    "    \"\"\"\n",
    "    Applies point mutations to a road trip. A point mutation swaps two waypoints.\n",
    "    \n",
    "    Args:\n",
    "        agent_genome (tuple): The sequence of waypoints to mutate.\n",
    "        max_mutations (int): The maximum number of swaps to perform.\n",
    "        \n",
    "    Returns:\n",
    "        tuple: The mutated sequence of waypoints.\n",
    "    \"\"\"\n",
    "    \n",
    "    agent_genome = list(agent_genome)\n",
    "    num_mutations = random.randint(1, max_mutations)\n",
    "    \n",
    "    for mutation in range(num_mutations):\n",
    "        swap_index1 = random.randint(0, len(agent_genome) - 1)\n",
    "        swap_index2 = swap_index1\n",
    "\n",
    "        while swap_index1 == swap_index2:\n",
    "            swap_index2 = random.randint(0, len(agent_genome) - 1)\n",
    "\n",
    "        agent_genome[swap_index1], agent_genome[swap_index2] = agent_genome[swap_index2], agent_genome[swap_index1]\n",
    "            \n",
    "    return tuple(agent_genome)\n",
    "\n",
    "def shuffle_mutation(agent_genome):\n",
    "    \"\"\"\n",
    "    Applies a shuffle mutation. A random sub-section of the route is moved to another location.\n",
    "    \n",
    "    Args:\n",
    "        agent_genome (tuple): The sequence of waypoints to mutate.\n",
    "        \n",
    "    Returns:\n",
    "        tuple: The mutated sequence of waypoints.\n",
    "    \"\"\"\n",
    "    \n",
    "    agent_genome = list(agent_genome)\n",
    "    \n",
    "    start_index = random.randint(0, len(agent_genome) - 1)\n",
    "    length = random.randint(2, 20)\n",
    "    \n",
    "    genome_subset = agent_genome[start_index:start_index + length]\n",
    "    agent_genome = agent_genome[:start_index] + agent_genome[start_index + length:]\n",
    "    \n",
    "    insert_index = random.randint(0, len(agent_genome) + len(genome_subset) - 1)\n",
    "    agent_genome = agent_genome[:insert_index] + genome_subset + agent_genome[insert_index:]\n",
    "    \n",
    "    return tuple(agent_genome)\n",
    "\n",
    "def generate_random_population(pop_size):\n",
    "    \"\"\"\n",
    "    Generates an initial population of random road trips.\n",
    "    \n",
    "    Args:\n",
    "        pop_size (int): The desired size of the population.\n",
    "        \n",
    "    Returns:\n",
    "        list: A list of randomly generated waypoint sequences.\n",
    "    \"\"\"\n",
    "    \n",
    "    random_population = []\n",
    "    for agent in range(pop_size):\n",
    "        random_population.append(generate_random_agent())\n",
    "    return random_population\n",
    "    \n",
    "def run_genetic_algorithm(generations=5000, population_size=100):\n",
    "    \"\"\"\n",
    "    Executes the genetic algorithm to find the shortest route.\n",
    "    \n",
    "    Args:\n",
    "        generations (int): The number of generations to run the algorithm.\n",
    "        population_size (int): The number of solutions in each generation.\n",
    "        \n",
    "    Returns:\n",
    "        tuple: The best route found.\n",
    "    \"\"\"\n",
    "    \n",
    "    current_best_distance = -1\n",
    "    population_subset_size = int(population_size / 10.)\n",
    "    generations_10pct = int(generations / 10.)\n",
    "    \n",
    "    # Create an initial random population.\n",
    "    population = generate_random_population(population_size)\n",
    "\n",
    "    # Main loop for generations.\n",
    "    for generation in range(generations):\n",
    "        \n",
    "        # Compute fitness for the entire population.\n",
    "        population_fitness = {}\n",
    "\n",
    "        for agent_genome in population:\n",
    "            if agent_genome in population_fitness:\n",
    "                continue\n",
    "            population_fitness[agent_genome] = compute_fitness(agent_genome)\n",
    "\n",
    "        # Select the top 10% fittest individuals to create the next generation.\n",
    "        new_population = []\n",
    "        for rank, agent_genome in enumerate(sorted(population_fitness,\n",
    "                                                   key=population_fitness.get)[:population_subset_size]):\n",
    "            # Display progress and save the best route periodically.\n",
    "            if (generation % generations_10pct == 0 or generation == generations - 1) and rank == 0:\n",
    "                current_best_genome = agent_genome\n",
    "                print(\"Generation %d best: %d | Unique genomes: %d\" % (generation,\n",
    "                                                                       population_fitness[agent_genome],\n",
    "                                                                       len(population_fitness)))\n",
    "                print(agent_genome)              \n",
    "                print(\"\")\n",
    "\n",
    "                if population_fitness[agent_genome] < current_best_distance or current_best_distance < 0:\n",
    "                    current_best_distance = population_fitness[agent_genome]\n",
    "                    CreateOptimalRouteHtmlFile(agent_genome, current_best_distance, False)\n",
    "                    \n",
    "\n",
    "            # Create offspring from the fittest individuals.\n",
    "            new_population.append(agent_genome)\n",
    "            for offspring in range(2):\n",
    "                new_population.append(mutate_agent(agent_genome, 3))\n",
    "            for offspring in range(7):\n",
    "                new_population.append(shuffle_mutation(agent_genome))\n",
    "\n",
    "        # Replace the old population with the new generation.\n",
    "        for i in range(len(population))[::-1]:\n",
    "            del population[i]\n",
    "        population = new_population\n",
    "    \n",
    "    return current_best_genome\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    print(\"Begin finding shortest route\")\n",
    "    file_path = waypoints_file\n",
    "    \n",
    "    # Check if a pre-computed waypoints file exists.\n",
    "    if os.path.exists(file_path):\n",
    "        print(\"Waypoints file found. Loading data.\")\n",
    "        waypoint_distances = {}\n",
    "        waypoint_durations = {}\n",
    "        all_waypoints = set()\n",
    "\n",
    "        waypoint_data = pd.read_csv(file_path, sep=\"\\t\")\n",
    "\n",
    "        for i, row in waypoint_data.iterrows():\n",
    "            waypoint_distances[frozenset([row.waypoint1, row.waypoint2])] = row.distance_m\n",
    "            waypoint_durations[frozenset([row.waypoint1, row.waypoint2])] = row.duration_s\n",
    "            all_waypoints.update([row.waypoint1, row.waypoint2])\n",
    "    else:\n",
    "        # If no file exists, use Google Maps API to compute distances.\n",
    "        print(\"Waypoints file not found. Collecting data from Google Maps.\")\n",
    "        waypoint_distances = {}\n",
    "        waypoint_durations = {}\n",
    "\n",
    "        gmaps = googlemaps.Client(GOOGLE_MAPS_API_KEY)\n",
    "        for (waypoint1, waypoint2) in combinations(all_waypoints, 2):\n",
    "            try:\n",
    "                route = gmaps.distance_matrix(origins=[waypoint1],\n",
    "                                              destinations=[waypoint2],\n",
    "                                              mode=\"driving\",\n",
    "                                              language=\"English\",\n",
    "                                              units=\"metric\")\n",
    "                distance = route[\"rows\"][0][\"elements\"][0][\"distance\"][\"value\"]\n",
    "                duration = route[\"rows\"][0][\"elements\"][0][\"duration\"][\"value\"]\n",
    "\n",
    "                waypoint_distances[frozenset([waypoint1, waypoint2])] = distance\n",
    "                waypoint_durations[frozenset([waypoint1, waypoint2])] = duration\n",
    "            \n",
    "            except Exception as e:\n",
    "                print(\"Error with finding the route between %s and %s.\" % (waypoint1, waypoint2))\n",
    "        \n",
    "        # Save the computed data to a file for future use.\n",
    "        print(\"Saving waypoints data.\")\n",
    "        with open(waypoints_file, \"w\") as out_file:\n",
    "            out_file.write(\"\\t\".join([\"waypoint1\",\n",
    "                                     \"waypoint2\",\n",
    "                                     \"distance_m\",\n",
    "                                     \"duration_s\"]))\n",
    "        \n",
    "            for (waypoint1, waypoint2) in waypoint_distances.keys():\n",
    "                out_file.write(\"\\n\" +\n",
    "                               \"\\t\".join([waypoint1,\n",
    "                                         waypoint2,\n",
    "                                         str(waypoint_distances[frozenset([waypoint1, waypoint2])]),\n",
    "                                         str(waypoint_durations[frozenset([waypoint1, waypoint2])])]))\n",
    "\n",
    "    # Run the genetic algorithm to find the optimal route.\n",
    "    print(\"Searching for optimal route.\")\n",
    "    optimal_route = run_genetic_algorithm(generations=thisRunGenerations, population_size=thisRunPopulation_size)\n",
    "\n",
    "    # Create and display the HTML file for the final best route.\n",
    "    CreateOptimalRouteHtmlFile(optimal_route, 1, True)"
   ]
  }
 ],
 "metadata": {
  "kaggle": {
   "accelerator": "none",
   "dataSources": [
    {
     "datasetId": 8310946,
     "sourceId": 13119574,
     "sourceType": "datasetVersion"
    }
   ],
   "dockerImageVersionId": 31089,
   "isGpuEnabled": false,
   "isInternetEnabled": true,
   "language": "python",
   "sourceType": "notebook"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.13"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 34.138774,
   "end_time": "2025-09-20T18:08:00.427207",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2025-09-20T18:07:26.288433",
   "version": "2.6.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
